### ISSUE TITLE
Why not reuse the connection in production env?

### ISSUE THREAD

**Issue by ogawa0071** [prisma/deployment-example-vercel#15]
https://github.com/prisma/deployment-example-vercel/blob/903ad88ffef160b5ffce18ba1344df41cc39cfa0/lib/prisma.js#L7-L9

**Comment by 2color** [comment]
Hey @ogawa0071,

The connection is actually reused in the example you show if there's a hot-start of a function. 

This logic is mostly to avoid instantiating too many instances of Prisma in development.

See more in the [docs](https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices#problem)
