### ISSUE TITLE
Add SSL instructions

### ISSUE THREAD

**Issue by villesau** [prisma/deployment-example-vercel#22]
Hi,

In order to deploy securely, you need SSL certificates, and e.g google cloud requires that. However there's no instructions on how to deploy to Vercel using SSL. Please add those instructions to complete the tutorial.

**Comment by janpio** [comment]
That is independent from this deployment example (Which really only focusses on the deployment) and would need to be part of the PRisma docs or similar. Please open an issue there if you can not find such instructions in the Prisma documentation. Thanks.
